server:
  port: 8081

spring:
  application:
    name: finance-dashboard-backend
  
  data:
    mongodb:
      uri: mongodb://localhost:27017/finance_dashboard
      database: finance_dashboard
  
  security:
    jwt:
      secret: your-256-bit-secret-key-here-make-it-long-and-secure
      expiration: 86400000 # 24 hours in milliseconds

# Gemini AI Configuration
gemini:
  api:
    key: your-gemini-api-key-here
    base-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# CORS Configuration
cors:
  allowed-origins: "http://localhost:3000,http://localhost:8080"
  allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.wealth.finance: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 